### PR TITLE
PAN-1703- Pokemon Sample Integration (Part 2)

### PR DESCRIPTION
**Pull request by EAHYoder**
[PAN-1703](https://greenwoodtech.atlassian.net/browse/PAN-1703?atlOrigin=eyJpIjoiYjU0NmE1NDM3ODM2NDgxNTkyNmMyN2U1YjJkNTUzZmUiLCJwIjoiaiJ9)

Changes:
This is the result of following part 2 of the pokemon tutorial
- Add the configs to the .yaml and env.default
- Since the configs are dynamic we add an init sync to populate their options.
- Alter the pokemonSync to use the new configs.

[PAN-1703]: https://greenwoodtech.atlassian.net/browse/PAN-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by guntur-ricardo — APPROVED** [review]
Do we want a customer logger class in this sample integration? I always find it odd to see console.error being used for normal logs. I know its because we don't capture that to stdout.

**Comment by EAHYoder** [comment]
> Do we want a customer logger class in this sample integration? I always find it odd to see console.error being used for normal logs. I know its because we don't capture that to stdout.


I've erred on the side of keeping things simpler in this integration.  I think it would be better to keep the sample integration stripped down but to add 2 things:
1- in the tutorial a link to the part of our docs where we explain how console.log is reserved for the standard out.
2- in the `Next Steps in learning to write Pandium integrations` section of the readme we can suggest they use a logging library

**Comment by guntur-ricardo** [comment]
> > Do we want a customer logger class in this sample integration? I always find it odd to see console.error being used for normal logs. I know its because we don't capture that to stdout.
> 
> I've erred on the side of keeping things simpler in this integration. I think it would be better to keep the sample integration stripped down but to add 2 things: 1- in the tutorial a link to the part of our docs where we explain how console.log is reserved for the standard out. 2- in the `Next Steps in learning to write Pandium integrations` section of the readme we can suggest they use a logging library

ok, it could be an addition to advanced tips somewhere else

**Review by sarahtrefethen — APPROVED** [review]
lgtm

**Pull request merged**
